export enum ErrorMessage {
  NOT_FOUND = "NOT_FOUND",
  INVALID_HEADERS = "INVALID_HEADERS",
  INVALID_TOKEN = "INVALID_TOKEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UNABLE_TO_PROCESS_ENTITY = "UNABLE_TO_PROCESS_ENTITY",
  ORGANIZATION_HAS_NO_VALIDATION_CONFIGURED = "ORGANIZATION_HAS_NO_VALIDATION_CONFIGURED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
