INSERT INTO subscriptions.subscription_plans (
  subscription_plan_id,
  subscription_plan_name,
  subscription_plan_product_id,
  subscription_plan_variants,
  subscription_plan_slug,
  subscription_plan_price,
  subscription_plan_final_price,
  subscription_plan_currency,
  subscription_plan_currency_symbol,
  subscription_plan_href,
  subscription_plan_billing_cycle,
  subscription_plan_description,
  subscription_plan_node_quota,
  subscription_plan_features,
  subscription_plan_most_popular,
  subscription_plan_tier,
  subscription_plan_is_active,
  subscription_plan_organization_client_id,
  subscription_plan_created_at,
  subscription_plan_updated_at
) VALUES(
  gen_random_uuid(),
  'Standard',
  '538854',
  '{}'::varchar[],
  '/standard-plan',
  4.0,
  3.0,
  'USD',
  '$',
  'https://****.lemonsqueezy.com/buy/b6314e3d-7ed1-468f-aef0-23b27b6d7f74',
  'monthly',
  'Standard Plan',
  100,
  '{"features":{"included":[{"name":"Customer Panel"},{"name":"Admin Panel"},{"name":"Mega Menu"},{"name":"Quick View"},{"name":"Quick Order"},{"name":"Live Message"},{"name":"Commercial use permission"}],"not_included":[{"name":"Analytics Dashboard"},{"name":"Priority Support"}]},"call_to_action":{"text":"Purchase Now","emoji":"🛒","url":"/purchase/commercial"}}'::jsonb,
  true,
  1,
  true,
  'SYK',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);
