export enum ErrorMessage {
  INSUFFICIENT_ACCESS_PERMISSIONS = "INSUFFICIENT_ACCESS_PERMISSIONS",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_HEADERS = "INVALID_HEADERS",
  INVALID_TOKEN = "INVALID_TOKEN",
  NOT_FOUND = "NOT_FOUND",
  ORGANIZATION_HAS_NO_VALIDATION_CONFIGURED = "ORGANIZATION_HAS_NO_VALIDATION_CONFIGURED",
  UNABLE_TO_PROCESS_ENTITY = "UNABLE_TO_PROCESS_ENTITY",
  NOT_HAVE_PERMISSION_TO_PERFORM_THIS_OPERATION = "NOT_HAVE_PERMISSION_TO_PERFORM_THIS_OPERATION",
  COULD_NOT_BE_CREATED_BECAUSE_ID_ALREADY_EXISTS = "COULD_NOT_BE_CREATED_BECAUSE_ID_ALREADY_EXISTS",
  FOREIGN_KEY_CONSTRAINT_FAILED = "FOREIGN_KEY_CONSTRAINT_FAILED",
  DATA_VALIDATION_FAILED = "DATA_VALIDATION_FAILED",

  // Feature Flag
  FEATURE_FLAG_NOT_FOUND = "FEATURE_FLAG_NOT_FOUND",

  // Configuration
  CONFIGURATION_NOT_FOUND = "CONFIGURATION_NOT_FOUND",

  // Organization
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",

  // ROLE
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",

  // PERMISSION
  PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND",

  // SUBSCRIPTION PLAN
  SUBSCRIPTION_PLAN_NOT_FOUND = "SUBSCRIPTION_PLAN_NOT_FOUND",

  // SUBSCRIPTION
  SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND",

  // PAYMENT
  PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND",

  // AUTHENTICATION
  INVALID_JWT_TOKEN = "INVALID_JWT_TOKEN",
  DELETING_USER_ERROR = "DELETING_USER_ERROR",
  SUPABASE_CONFIGURATION_NOT_FOUND = "SUPABASE_CONFIGURATION_NOT_FOUND",
  FIREBASE_CONFIGURATION_NOT_FOUND = "FIREBASE_CONFIGURATION_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",

  // UTILS
  JSON_DECODING_ERROR = "JSON_DECODING_ERROR",

  // USER
  USER_NOT_FOUND = "USER_NOT_FOUND",

  // STATSIG
  YOU_CANNOT_CREATE_CONFIGURATIONS = "OPERATION_NOT_ALLOWED_YOU_CANNOT_CREATE_CONFIGURATIONS_USING_STATSIG_SDK",
  CONFIGURATIONS_MUST_BE_MANAGED_VIA_THE_STATSIG_CONSOLE = "OPERATION_NOT_ALLOWED_CONFIGURATIONS_MUST_BE_MANAGED_VIA_THE_STATSIG_CONSOLE",
  DELETING_CONFIGURATIONS_IS_NOT_SUPPORTED_BY_THE_STATSIG_SDK = "OPERATION_NOT_ALLOWED_DELETING_CONFIGURATIONS_IS_NOT_SUPPORTED_BY_THE_STATSIG_SDK",
}
