"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorMessage = void 0;
var ErrorMessage;
(function (ErrorMessage) {
    ErrorMessage["INSUFFICIENT_ACCESS_PERMISSIONS"] = "INSUFFICIENT_ACCESS_PERMISSIONS";
    ErrorMessage["INTERNAL_SERVER_ERROR"] = "INTERNAL_SERVER_ERROR";
    ErrorMessage["INVALID_CREDENTIALS"] = "INVALID_CREDENTIALS";
    ErrorMessage["INVALID_HEADERS"] = "INVALID_HEADERS";
    ErrorMessage["INVALID_TOKEN"] = "INVALID_TOKEN";
    ErrorMessage["NOT_FOUND"] = "NOT_FOUND";
    ErrorMessage["ORGANIZATION_HAS_NO_VALIDATION_CONFIGURED"] = "ORGANIZATION_HAS_NO_VALIDATION_CONFIGURED";
    ErrorMessage["UNABLE_TO_PROCESS_ENTITY"] = "UNABLE_TO_PROCESS_ENTITY";
    ErrorMessage["NOT_HAVE_PERMISSION_TO_PERFORM_THIS_OPERATION"] = "NOT_HAVE_PERMISSION_TO_PERFORM_THIS_OPERATION";
    ErrorMessage["COULD_NOT_BE_CREATED_BECAUSE_ID_ALREADY_EXISTS"] = "COULD_NOT_BE_CREATED_BECAUSE_ID_ALREADY_EXISTS";
    ErrorMessage["FOREIGN_KEY_CONSTRAINT_FAILED"] = "FOREIGN_KEY_CONSTRAINT_FAILED";
    ErrorMessage["DATA_VALIDATION_FAILED"] = "DATA_VALIDATION_FAILED";
    // Feature Flag
    ErrorMessage["FEATURE_FLAG_NOT_FOUND"] = "FEATURE_FLAG_NOT_FOUND";
    // Configuration
    ErrorMessage["CONFIGURATION_NOT_FOUND"] = "CONFIGURATION_NOT_FOUND";
    // Organization
    ErrorMessage["ORGANIZATION_NOT_FOUND"] = "ORGANIZATION_NOT_FOUND";
    // ROLE
    ErrorMessage["ROLE_NOT_FOUND"] = "ROLE_NOT_FOUND";
    // PERMISSION
    ErrorMessage["PERMISSION_NOT_FOUND"] = "PERMISSION_NOT_FOUND";
})(ErrorMessage || (exports.ErrorMessage = ErrorMessage = {}));
