export enum ErrorMessage {
  INSUFFICIENT_ACCESS_PERMISSIONS = "INSUFFICIENT_ACCESS_PERMISSIONS",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_HEADERS = "INVALID_HEADERS",
  INVALID_TOKEN = "INVALID_TOKEN",
  NOT_FOUND = "NOT_FOUND",
  ORGANIZATION_HAS_NO_VALIDATION_CONFIGURED = "ORGANIZATION_HAS_NO_VALIDATION_CONFIGURED",
  UNABLE_TO_PROCESS_ENTITY = "UNABLE_TO_PROCESS_ENTITY",
  NOT_HAVE_PERMISSION_TO_PERFORM_THIS_OPERATION = "NOT_HAVE_PERMISSION_TO_PERFORM_THIS_OPERATION",
  COULD_NOT_BE_CREATED_BECAUSE_ID_ALREADY_EXISTS = "COULD_NOT_BE_CREATED_BECAUSE_ID_ALREADY_EXISTS",
  FOREIGN_KEY_CONSTRAINT_FAILED = "FOREIGN_KEY_CONSTRAINT_FAILED",
  DATA_VALIDATION_FAILED = "DATA_VALIDATION_FAILED",

  // Feature Flag
  FEATURE_FLAG_NOT_FOUND = "FEATURE_FLAG_NOT_FOUND",

  // Configuration
  CONFIGURATION_NOT_FOUND = "CONFIGURATION_NOT_FOUND",

  // Organization
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",

  // ROLE
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",

  // PERMISSION
  PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND",

  // SUBSCRIPTION PLAN
  SUBSCRIPTION_PLAN_NOT_FOUND = "SUBSCRIPTION_PLAN_NOT_FOUND",

  // SUBSCRIPTION
  SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND",
}
